export const surpriseMePrompts = [
  'A futuristic cityscape at sunset with flying cars and neon-lit skyscrapers reflecting in a rain-soaked street',
  'An enchanted forest with glowing mushrooms, mystical creatures, and shafts of moonlight piercing the canopy',
  'A lone astronaut standing on a distant exoplanet with twin moons rising over jagged purple mountains',
  'A photorealistic portrait of a cyberpunk samurai in rain-drenched Tokyo at night, neon reflections on their armor',
  'An underwater palace carved from coral, illuminated by bioluminescent sea creatures and sunken treasure',
  'A giant ancient tree with a hidden village inside, lanterns glowing from tiny windows at twilight',
  'A surrealist painting of melting clocks draped over a desert landscape, inspired by Salvador Dalí, ultra-detailed',
  'A dramatic aerial view of Machu Picchu wrapped in morning mist, golden sunrise breaking over the Andes',
  'A cozy futuristic café on a space station with a panoramic window showing the Milky Way galaxy',
  'An epic fantasy battle scene — dragon riders clashing above a burning medieval fortress in a lightning storm',
  'A hyper-detailed still life of exotic tropical fruits arranged in an ornate golden bowl, Renaissance oil painting style',
  'A lone wolf howling at an aurora borealis above a frozen tundra, stars reflecting in an ice lake below',
  'A whimsical steampunk hot-air balloon festival over Victorian London at dusk, golden cogs and gears everywhere',
  'A microscopic world inside a dewdrop on a leaf — tiny castles, trees, and a rainbow refracted inside',
  'An Art Deco poster of a retro-futuristic rocket ship launching from the Moon toward Earth, vintage color palette',
  'A photorealistic cheetah wearing a golden crown seated on an ancient throne, draped in royal robes',
  'A zen garden in autumn with vibrant red and orange maple leaves falling onto raked white sand patterns',
  'A towering alien megastructure — a Dyson sphere under construction around a dying red-giant star',
  'A magical library with infinite spiraling bookshelves, soft candlelight, floating books, and a reading nook on a cloud',
  'An ultra-detailed macro photograph of a peacock feather revealing an entire galaxy within its eye pattern',
];
