import React, { useState, useEffect } from 'react';
import { Card, FormField, Loader } from '../components';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase col-span-full text-center">
      {title}
    </h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState('');
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      try {
        const response = await fetch('/api/v1/post', {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' },
        });
        if (response.ok) {
          const result = await response.json();
          setAllPosts(result.data);
        }
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    };
    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);
    setSearchTimeout(
      setTimeout(() => {
        const filtered = allPosts?.filter(
          (post) =>
            post.name.toLowerCase().includes(e.target.value.toLowerCase()) ||
            post.prompt.toLowerCase().includes(e.target.value.toLowerCase())
        );
        setSearchedResults(filtered);
      }, 500)
    );
  };

  return (
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="mb-10">
        <h1 className="text-5xl sm:text-6xl font-extrabold tracking-tight bg-gradient-to-r from-[#f0f0f5] to-[#9898b0] bg-clip-text text-transparent leading-tight">
          Community<br />Showcase
        </h1>
        <p className="mt-4 text-[#9898b0] text-lg leading-relaxed max-w-xl">
          Explore a collection of imaginative and visually stunning images generated by our community using the power of AI.
        </p>
      </div>

      <div className="mb-10 max-w-xl">
        <FormField
          labelName="Search posts"
          type="text"
          name="search"
          placeholder="Search by name or prompt..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      <div className="mt-8">
        {loading ? (
          <div className="flex items-center justify-center min-h-[300px]">
            <Loader size="lg" />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#9898b0] text-sm mb-4">
                Showing results for{' '}
                <span className="text-[#f0f0f5] font-semibold">"{searchText}"</span>
              </h2>
            )}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
              {searchText ? (
                <RenderCards data={searchedResults} title="No search results found" />
              ) : (
                <RenderCards data={allPosts} title="No posts yet — be the first to create one!" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
